apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/order-app
  newName: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/order-app
  newTag: 75c2b7f5
- name: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/order}-app
  newName: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/order-app
  newTag: 02e95cf7
resources:
- ../../base
patchesStrategicMerge:
- order-deployment-patch.yaml
